name: 'dbt_tiki'
version: '1.0.0'
config-version: 2

profile: 'dbt_tiki'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets: 
  - "target"
  - "dbt_packages"

models:
  dbt_tiki:
    staging:
      +materialized: table
      +schema: staging
    marts:
      dimensions:
        +materialized: incremental
        +schema: dimensions
        +incremental_strategy: merge
        +on_schema_change: sync_all_columns
      facts:
        +materialized: incremental
        +schema: facts
        +incremental_strategy: append
        +on_schema_change: sync_all_columns
